### ISSUE TITLE
.onion down

### ISSUE THREAD

**Issue by Plazmaz** [alexhaydock/DarkwebKittens#2]
Hi, it looks like your .onion link (kitten3wusb6j26ukqae5cioarrademwlaoa5sria4uporcstbkdflid.onion) is down.

**Comment by alexhaydock** [comment]
You were quick to notice that!

I’ve been experimenting with automating the deployment of onion services with Terraform and Ansible today, and that’s left it in a not-quite-working state.

Hopefully with a bit more config it’ll work again tomorrow.

**Comment by Plazmaz** [comment]
Darkweb kittens are _very_ important to me. Thank you.

**Comment by alexhaydock** [comment]
Should be back up now. The kittens have returned! 🐱

**Comment by Plazmaz** [comment]
hmm still having trouble hitting it. Is it at `kitten3wusb6j26ukqae5cioarrademwlaoa5sria4uporcstbkdflid.onion`?

**Comment by alexhaydock** [comment]
Try again :wink: I was redeploying just as you commented.

**Comment by Plazmaz** [comment]
Hooray! Apparently I have especially bad timing skills.

**Comment by alexhaydock** [comment]
It should be more stable now too since I finished messing with it.

Though this is really just my domain for testing random stuff, so I can't guarantee 99.9% uptime or anything. If you do find yourself needing permanent kittens, feel free to just take the Docker container and stick it somewhere.

I need to sort out the `LICENSE` file actually, but all the pictures are from Flickr and licensed Creative Commons.
